// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'database/models/account_custom_field.dart';
import 'database/models/account_ojb_model.dart';
import 'database/models/category_ojb_model.dart';
import 'database/models/icon_custom_model.dart';
import 'database/models/password_history_model.dart';
import 'database/models/totp_ojb_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 2383928923318499737),
      name: 'AccountCustomFieldOjbModel',
      lastPropertyId: const obx_int.IdUid(6, 5630134015553611220),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4090243857449051327),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 8108096208718074723),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8130378122510920081),
            name: 'value',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 195803133803081672),
            name: 'hintText',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 1528464119627355137),
            name: 'typeField',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 5630134015553611220),
            name: 'accountId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(1, 3516835503781729309),
            relationTarget: 'AccountOjbModel')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 1878628315045204891),
      name: 'AccountOjbModel',
      lastPropertyId: const obx_int.IdUid(12, 2840453311877770067),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 1372285699841932207),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 4300649734842015689),
            name: 'title',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8825276413177178007),
            name: 'email',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 2443423335981930991),
            name: 'password',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 4271078033416534245),
            name: 'notes',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 3461382277341645239),
            name: 'icon',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 2096088798621611869),
            name: 'passwordUpdatedAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 3636003688389024147),
            name: 'createdAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 7012549897201973190),
            name: 'updatedAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 6070888810759960578),
            name: 'categoryId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(2, 1428949723357222232),
            relationTarget: 'CategoryOjbModel'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 7392309477732683641),
            name: 'iconCustomId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(3, 2785332030754345948),
            relationTarget: 'IconCustomModel'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 2840453311877770067),
            name: 'totpId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(4, 5902132704694811328),
            relationTarget: 'TOTPOjbModel')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[
        obx_int.ModelBacklink(
            name: 'customFields',
            srcEntity: 'AccountCustomFieldOjbModel',
            srcField: 'account'),
        obx_int.ModelBacklink(
            name: 'passwordHistories',
            srcEntity: 'PasswordHistory',
            srcField: 'account')
      ]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(4, 7418765908887414954),
      name: 'CategoryOjbModel',
      lastPropertyId: const obx_int.IdUid(7, 5516788290996013881),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3137172756682708238),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 8885917553095961023),
            name: 'categoryName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8159939972600516598),
            name: 'icon',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 1818112331230895039),
            name: 'color',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 5584116146259932664),
            name: 'indexPos',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 3896970218096645113),
            name: 'createdAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 5516788290996013881),
            name: 'updatedAt',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[
        obx_int.ModelBacklink(
            name: 'accounts',
            srcEntity: 'AccountOjbModel',
            srcField: 'category')
      ]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(5, 3055995045590780828),
      name: 'IconCustomModel',
      lastPropertyId: const obx_int.IdUid(6, 4362901113340552298),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6294659331695565505),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2757664982512354282),
            name: 'path',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 7015245297783846823),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 8233014793896729974),
            name: 'color',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 4115719657313187141),
            name: 'createdAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 4362901113340552298),
            name: 'updatedAt',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[
        obx_int.ModelBacklink(
            name: 'accounts',
            srcEntity: 'AccountOjbModel',
            srcField: 'iconCustom')
      ]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(6, 2551119760188800600),
      name: 'PasswordHistory',
      lastPropertyId: const obx_int.IdUid(5, 6986931833305867789),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3077352258078751429),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 4186192472090827493),
            name: 'password',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 1488242565971585751),
            name: 'createdAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 5826854046891571145),
            name: 'updatedAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 6986931833305867789),
            name: 'accountId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(5, 7939173635836407566),
            relationTarget: 'AccountOjbModel')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(8, 7120869973844560665),
      name: 'TOTPOjbModel',
      lastPropertyId: const obx_int.IdUid(9, 7340138041424992946),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7287059395120116218),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 1233602503582447821),
            name: 'secretKey',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(7, 5998668159314400233)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 1904737723347952021),
            name: 'algorithm',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(8, 5371294220000771482)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 6206671128466549134),
            name: 'digits',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 1733067822921561598),
            name: 'period',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 9218111210333108305),
            name: 'isShowToHome',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 2249178839472043866),
            name: 'createdAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 3039338650922470844),
            name: 'updatedAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 7340138041424992946),
            name: 'accountId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(9, 3150162145201670091),
            relationTarget: 'AccountOjbModel')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(8, 7120869973844560665),
      lastIndexId: const obx_int.IdUid(9, 3150162145201670091),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [4576241909475943585, 6213000607887385064],
      retiredIndexUids: const [],
      retiredPropertyUids: const [
        2342124192628778866,
        3504522657512904849,
        3078649058524668291,
        4374515946613989280,
        7006581877455254584,
        2274224845818563168,
        5993330135503332106,
        3251973262211811324,
        8847343354232474621,
        3223109459863103305,
        5418969512423873346,
        1473061717587223460,
        5751746544805988232,
        5284008716632940634,
        5508023974651288282,
        2179601716462441340,
        9157959535894620892,
        4155842190920700882,
        6711675260948032995,
        8055032713108837086,
        8096244496920815466
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    AccountCustomFieldOjbModel: obx_int.EntityDefinition<
            AccountCustomFieldOjbModel>(
        model: _entities[0],
        toOneRelations: (AccountCustomFieldOjbModel object) => [object.account],
        toManyRelations: (AccountCustomFieldOjbModel object) => {},
        getId: (AccountCustomFieldOjbModel object) => object.id,
        setId: (AccountCustomFieldOjbModel object, int id) {
          object.id = id;
        },
        objectToFB: (AccountCustomFieldOjbModel object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final valueOffset = fbb.writeString(object.value);
          final hintTextOffset = fbb.writeString(object.hintText);
          final typeFieldOffset = fbb.writeString(object.typeField);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, valueOffset);
          fbb.addOffset(3, hintTextOffset);
          fbb.addOffset(4, typeFieldOffset);
          fbb.addInt64(5, object.account.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final valueParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final hintTextParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final typeFieldParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final object = AccountCustomFieldOjbModel(
              id: idParam,
              name: nameParam,
              value: valueParam,
              hintText: hintTextParam,
              typeField: typeFieldParam);
          object.account.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          object.account.attach(store);
          return object;
        }),
    AccountOjbModel: obx_int.EntityDefinition<AccountOjbModel>(
        model: _entities[1],
        toOneRelations: (AccountOjbModel object) =>
            [object.category, object.iconCustom, object.totp],
        toManyRelations: (AccountOjbModel object) => {
              obx_int.RelInfo<AccountCustomFieldOjbModel>.toOneBacklink(
                  6,
                  object.id,
                  (AccountCustomFieldOjbModel srcObject) =>
                      srcObject.account): object.customFields,
              obx_int.RelInfo<PasswordHistory>.toOneBacklink(5, object.id,
                      (PasswordHistory srcObject) => srcObject.account):
                  object.passwordHistories
            },
        getId: (AccountOjbModel object) => object.id,
        setId: (AccountOjbModel object, int id) {
          object.id = id;
        },
        objectToFB: (AccountOjbModel object, fb.Builder fbb) {
          final titleOffset = fbb.writeString(object.title);
          final emailOffset =
              object.email == null ? null : fbb.writeString(object.email!);
          final passwordOffset = object.password == null
              ? null
              : fbb.writeString(object.password!);
          final notesOffset =
              object.notes == null ? null : fbb.writeString(object.notes!);
          final iconOffset =
              object.icon == null ? null : fbb.writeString(object.icon!);
          fbb.startTable(13);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, titleOffset);
          fbb.addOffset(2, emailOffset);
          fbb.addOffset(3, passwordOffset);
          fbb.addOffset(4, notesOffset);
          fbb.addOffset(5, iconOffset);
          fbb.addInt64(6, object.passwordUpdatedAt?.millisecondsSinceEpoch);
          fbb.addInt64(7, object.createdAt?.millisecondsSinceEpoch);
          fbb.addInt64(8, object.updatedAt?.millisecondsSinceEpoch);
          fbb.addInt64(9, object.category.targetId);
          fbb.addInt64(10, object.iconCustom.targetId);
          fbb.addInt64(11, object.totp.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final passwordUpdatedAtValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 16);
          final createdAtValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 18);
          final updatedAtValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 20);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final titleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final emailParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 8);
          final passwordParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final notesParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 12);
          final iconParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 14);
          final passwordUpdatedAtParam = passwordUpdatedAtValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(passwordUpdatedAtValue);
          final createdAtParam = createdAtValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(createdAtValue);
          final updatedAtParam = updatedAtValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(updatedAtValue);
          final object = AccountOjbModel(
              id: idParam,
              title: titleParam,
              email: emailParam,
              password: passwordParam,
              notes: notesParam,
              icon: iconParam,
              passwordUpdatedAt: passwordUpdatedAtParam,
              createdAt: createdAtParam,
              updatedAt: updatedAtParam);
          object.category.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0);
          object.category.attach(store);
          object.iconCustom.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0);
          object.iconCustom.attach(store);
          object.totp.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 26, 0);
          object.totp.attach(store);
          obx_int.InternalToManyAccess.setRelInfo<AccountOjbModel>(
              object.customFields,
              store,
              obx_int.RelInfo<AccountCustomFieldOjbModel>.toOneBacklink(
                  6,
                  object.id,
                  (AccountCustomFieldOjbModel srcObject) => srcObject.account));
          obx_int.InternalToManyAccess.setRelInfo<AccountOjbModel>(
              object.passwordHistories,
              store,
              obx_int.RelInfo<PasswordHistory>.toOneBacklink(5, object.id,
                  (PasswordHistory srcObject) => srcObject.account));
          return object;
        }),
    CategoryOjbModel: obx_int.EntityDefinition<CategoryOjbModel>(
        model: _entities[2],
        toOneRelations: (CategoryOjbModel object) => [],
        toManyRelations: (CategoryOjbModel object) => {
              obx_int.RelInfo<AccountOjbModel>.toOneBacklink(10, object.id,
                      (AccountOjbModel srcObject) => srcObject.category):
                  object.accounts
            },
        getId: (CategoryOjbModel object) => object.id,
        setId: (CategoryOjbModel object, int id) {
          object.id = id;
        },
        objectToFB: (CategoryOjbModel object, fb.Builder fbb) {
          final categoryNameOffset = fbb.writeString(object.categoryName);
          final iconOffset =
              object.icon == null ? null : fbb.writeString(object.icon!);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, categoryNameOffset);
          fbb.addOffset(2, iconOffset);
          fbb.addInt64(3, object.color);
          fbb.addInt64(4, object.indexPos);
          fbb.addInt64(5, object.createdAt.millisecondsSinceEpoch);
          fbb.addInt64(6, object.updatedAt.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final categoryNameParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, '');
          final iconParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 8);
          final colorParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 10);
          final indexPosParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0));
          final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0));
          final object = CategoryOjbModel(
              id: idParam,
              categoryName: categoryNameParam,
              icon: iconParam,
              color: colorParam,
              indexPos: indexPosParam,
              createdAt: createdAtParam,
              updatedAt: updatedAtParam);
          obx_int.InternalToManyAccess.setRelInfo<CategoryOjbModel>(
              object.accounts,
              store,
              obx_int.RelInfo<AccountOjbModel>.toOneBacklink(10, object.id,
                  (AccountOjbModel srcObject) => srcObject.category));
          return object;
        }),
    IconCustomModel: obx_int.EntityDefinition<IconCustomModel>(
        model: _entities[3],
        toOneRelations: (IconCustomModel object) => [],
        toManyRelations: (IconCustomModel object) => {
              obx_int.RelInfo<AccountOjbModel>.toOneBacklink(11, object.id,
                      (AccountOjbModel srcObject) => srcObject.iconCustom):
                  object.accounts
            },
        getId: (IconCustomModel object) => object.id,
        setId: (IconCustomModel object, int id) {
          object.id = id;
        },
        objectToFB: (IconCustomModel object, fb.Builder fbb) {
          final pathOffset = fbb.writeString(object.path);
          final nameOffset =
              object.name == null ? null : fbb.writeString(object.name!);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, pathOffset);
          fbb.addOffset(2, nameOffset);
          fbb.addInt64(3, object.color);
          fbb.addInt64(4, object.createdAt.millisecondsSinceEpoch);
          fbb.addInt64(5, object.updatedAt.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final pathParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 8);
          final colorParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 10);
          final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0));
          final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0));
          final object = IconCustomModel(
              id: idParam,
              path: pathParam,
              name: nameParam,
              color: colorParam,
              createdAt: createdAtParam,
              updatedAt: updatedAtParam);
          obx_int.InternalToManyAccess.setRelInfo<IconCustomModel>(
              object.accounts,
              store,
              obx_int.RelInfo<AccountOjbModel>.toOneBacklink(11, object.id,
                  (AccountOjbModel srcObject) => srcObject.iconCustom));
          return object;
        }),
    PasswordHistory: obx_int.EntityDefinition<PasswordHistory>(
        model: _entities[4],
        toOneRelations: (PasswordHistory object) => [object.account],
        toManyRelations: (PasswordHistory object) => {},
        getId: (PasswordHistory object) => object.id,
        setId: (PasswordHistory object, int id) {
          object.id = id;
        },
        objectToFB: (PasswordHistory object, fb.Builder fbb) {
          final passwordOffset = fbb.writeString(object.password);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, passwordOffset);
          fbb.addInt64(2, object.createdAt.millisecondsSinceEpoch);
          fbb.addInt64(3, object.updatedAt.millisecondsSinceEpoch);
          fbb.addInt64(4, object.account.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final passwordParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0));
          final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0));
          final object = PasswordHistory(
              id: idParam,
              password: passwordParam,
              createdAt: createdAtParam,
              updatedAt: updatedAtParam);
          object.account.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          object.account.attach(store);
          return object;
        }),
    TOTPOjbModel: obx_int.EntityDefinition<TOTPOjbModel>(
        model: _entities[5],
        toOneRelations: (TOTPOjbModel object) => [object.account],
        toManyRelations: (TOTPOjbModel object) => {},
        getId: (TOTPOjbModel object) => object.id,
        setId: (TOTPOjbModel object, int id) {
          object.id = id;
        },
        objectToFB: (TOTPOjbModel object, fb.Builder fbb) {
          final secretKeyOffset = fbb.writeString(object.secretKey);
          final algorithmOffset = object.algorithm == null
              ? null
              : fbb.writeString(object.algorithm!);
          fbb.startTable(10);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, secretKeyOffset);
          fbb.addOffset(2, algorithmOffset);
          fbb.addInt64(3, object.digits);
          fbb.addInt64(4, object.period);
          fbb.addBool(5, object.isShowToHome);
          fbb.addInt64(6, object.createdAt.millisecondsSinceEpoch);
          fbb.addInt64(7, object.updatedAt.millisecondsSinceEpoch);
          fbb.addInt64(8, object.account.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final secretKeyParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final algorithmParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 8);
          final digitsParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final periodParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final isShowToHomeParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 14, false);
          final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0));
          final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0));
          final object = TOTPOjbModel(
              id: idParam,
              secretKey: secretKeyParam,
              algorithm: algorithmParam,
              digits: digitsParam,
              period: periodParam,
              isShowToHome: isShowToHomeParam,
              createdAt: createdAtParam,
              updatedAt: updatedAtParam);
          object.account.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0);
          object.account.attach(store);
          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [AccountCustomFieldOjbModel] entity fields to define ObjectBox queries.
class AccountCustomFieldOjbModel_ {
  /// See [AccountCustomFieldOjbModel.id].
  static final id = obx.QueryIntegerProperty<AccountCustomFieldOjbModel>(
      _entities[0].properties[0]);

  /// See [AccountCustomFieldOjbModel.name].
  static final name = obx.QueryStringProperty<AccountCustomFieldOjbModel>(
      _entities[0].properties[1]);

  /// See [AccountCustomFieldOjbModel.value].
  static final value = obx.QueryStringProperty<AccountCustomFieldOjbModel>(
      _entities[0].properties[2]);

  /// See [AccountCustomFieldOjbModel.hintText].
  static final hintText = obx.QueryStringProperty<AccountCustomFieldOjbModel>(
      _entities[0].properties[3]);

  /// See [AccountCustomFieldOjbModel.typeField].
  static final typeField = obx.QueryStringProperty<AccountCustomFieldOjbModel>(
      _entities[0].properties[4]);

  /// See [AccountCustomFieldOjbModel.account].
  static final account =
      obx.QueryRelationToOne<AccountCustomFieldOjbModel, AccountOjbModel>(
          _entities[0].properties[5]);
}

/// [AccountOjbModel] entity fields to define ObjectBox queries.
class AccountOjbModel_ {
  /// See [AccountOjbModel.id].
  static final id =
      obx.QueryIntegerProperty<AccountOjbModel>(_entities[1].properties[0]);

  /// See [AccountOjbModel.title].
  static final title =
      obx.QueryStringProperty<AccountOjbModel>(_entities[1].properties[1]);

  /// See [AccountOjbModel.email].
  static final email =
      obx.QueryStringProperty<AccountOjbModel>(_entities[1].properties[2]);

  /// See [AccountOjbModel.password].
  static final password =
      obx.QueryStringProperty<AccountOjbModel>(_entities[1].properties[3]);

  /// See [AccountOjbModel.notes].
  static final notes =
      obx.QueryStringProperty<AccountOjbModel>(_entities[1].properties[4]);

  /// See [AccountOjbModel.icon].
  static final icon =
      obx.QueryStringProperty<AccountOjbModel>(_entities[1].properties[5]);

  /// See [AccountOjbModel.passwordUpdatedAt].
  static final passwordUpdatedAt =
      obx.QueryDateProperty<AccountOjbModel>(_entities[1].properties[6]);

  /// See [AccountOjbModel.createdAt].
  static final createdAt =
      obx.QueryDateProperty<AccountOjbModel>(_entities[1].properties[7]);

  /// See [AccountOjbModel.updatedAt].
  static final updatedAt =
      obx.QueryDateProperty<AccountOjbModel>(_entities[1].properties[8]);

  /// See [AccountOjbModel.category].
  static final category =
      obx.QueryRelationToOne<AccountOjbModel, CategoryOjbModel>(
          _entities[1].properties[9]);

  /// See [AccountOjbModel.iconCustom].
  static final iconCustom =
      obx.QueryRelationToOne<AccountOjbModel, IconCustomModel>(
          _entities[1].properties[10]);

  /// See [AccountOjbModel.totp].
  static final totp = obx.QueryRelationToOne<AccountOjbModel, TOTPOjbModel>(
      _entities[1].properties[11]);

  /// see [AccountOjbModel.customFields]
  static final customFields =
      obx.QueryBacklinkToMany<AccountCustomFieldOjbModel, AccountOjbModel>(
          AccountCustomFieldOjbModel_.account);

  /// see [AccountOjbModel.passwordHistories]
  static final passwordHistories =
      obx.QueryBacklinkToMany<PasswordHistory, AccountOjbModel>(
          PasswordHistory_.account);
}

/// [CategoryOjbModel] entity fields to define ObjectBox queries.
class CategoryOjbModel_ {
  /// See [CategoryOjbModel.id].
  static final id =
      obx.QueryIntegerProperty<CategoryOjbModel>(_entities[2].properties[0]);

  /// See [CategoryOjbModel.categoryName].
  static final categoryName =
      obx.QueryStringProperty<CategoryOjbModel>(_entities[2].properties[1]);

  /// See [CategoryOjbModel.icon].
  static final icon =
      obx.QueryStringProperty<CategoryOjbModel>(_entities[2].properties[2]);

  /// See [CategoryOjbModel.color].
  static final color =
      obx.QueryIntegerProperty<CategoryOjbModel>(_entities[2].properties[3]);

  /// See [CategoryOjbModel.indexPos].
  static final indexPos =
      obx.QueryIntegerProperty<CategoryOjbModel>(_entities[2].properties[4]);

  /// See [CategoryOjbModel.createdAt].
  static final createdAt =
      obx.QueryDateProperty<CategoryOjbModel>(_entities[2].properties[5]);

  /// See [CategoryOjbModel.updatedAt].
  static final updatedAt =
      obx.QueryDateProperty<CategoryOjbModel>(_entities[2].properties[6]);

  /// see [CategoryOjbModel.accounts]
  static final accounts =
      obx.QueryBacklinkToMany<AccountOjbModel, CategoryOjbModel>(
          AccountOjbModel_.category);
}

/// [IconCustomModel] entity fields to define ObjectBox queries.
class IconCustomModel_ {
  /// See [IconCustomModel.id].
  static final id =
      obx.QueryIntegerProperty<IconCustomModel>(_entities[3].properties[0]);

  /// See [IconCustomModel.path].
  static final path =
      obx.QueryStringProperty<IconCustomModel>(_entities[3].properties[1]);

  /// See [IconCustomModel.name].
  static final name =
      obx.QueryStringProperty<IconCustomModel>(_entities[3].properties[2]);

  /// See [IconCustomModel.color].
  static final color =
      obx.QueryIntegerProperty<IconCustomModel>(_entities[3].properties[3]);

  /// See [IconCustomModel.createdAt].
  static final createdAt =
      obx.QueryDateProperty<IconCustomModel>(_entities[3].properties[4]);

  /// See [IconCustomModel.updatedAt].
  static final updatedAt =
      obx.QueryDateProperty<IconCustomModel>(_entities[3].properties[5]);

  /// see [IconCustomModel.accounts]
  static final accounts =
      obx.QueryBacklinkToMany<AccountOjbModel, IconCustomModel>(
          AccountOjbModel_.iconCustom);
}

/// [PasswordHistory] entity fields to define ObjectBox queries.
class PasswordHistory_ {
  /// See [PasswordHistory.id].
  static final id =
      obx.QueryIntegerProperty<PasswordHistory>(_entities[4].properties[0]);

  /// See [PasswordHistory.password].
  static final password =
      obx.QueryStringProperty<PasswordHistory>(_entities[4].properties[1]);

  /// See [PasswordHistory.createdAt].
  static final createdAt =
      obx.QueryDateProperty<PasswordHistory>(_entities[4].properties[2]);

  /// See [PasswordHistory.updatedAt].
  static final updatedAt =
      obx.QueryDateProperty<PasswordHistory>(_entities[4].properties[3]);

  /// See [PasswordHistory.account].
  static final account =
      obx.QueryRelationToOne<PasswordHistory, AccountOjbModel>(
          _entities[4].properties[4]);
}

/// [TOTPOjbModel] entity fields to define ObjectBox queries.
class TOTPOjbModel_ {
  /// See [TOTPOjbModel.id].
  static final id =
      obx.QueryIntegerProperty<TOTPOjbModel>(_entities[5].properties[0]);

  /// See [TOTPOjbModel.secretKey].
  static final secretKey =
      obx.QueryStringProperty<TOTPOjbModel>(_entities[5].properties[1]);

  /// See [TOTPOjbModel.algorithm].
  static final algorithm =
      obx.QueryStringProperty<TOTPOjbModel>(_entities[5].properties[2]);

  /// See [TOTPOjbModel.digits].
  static final digits =
      obx.QueryIntegerProperty<TOTPOjbModel>(_entities[5].properties[3]);

  /// See [TOTPOjbModel.period].
  static final period =
      obx.QueryIntegerProperty<TOTPOjbModel>(_entities[5].properties[4]);

  /// See [TOTPOjbModel.isShowToHome].
  static final isShowToHome =
      obx.QueryBooleanProperty<TOTPOjbModel>(_entities[5].properties[5]);

  /// See [TOTPOjbModel.createdAt].
  static final createdAt =
      obx.QueryDateProperty<TOTPOjbModel>(_entities[5].properties[6]);

  /// See [TOTPOjbModel.updatedAt].
  static final updatedAt =
      obx.QueryDateProperty<TOTPOjbModel>(_entities[5].properties[7]);

  /// See [TOTPOjbModel.account].
  static final account = obx.QueryRelationToOne<TOTPOjbModel, AccountOjbModel>(
      _entities[5].properties[8]);
}
